services:
  # ===== Backend API =====
  - type: web
    name: wastage-backend
    env: python
    region: frankfurt
    plan: starter
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    workingDirectory: backend
    autoDeploy: true

    # If you want CORS to allow frontend domain:
    envVars:
      - key: PYTHON_VERSION
        value: 3.11


  # ===== Frontend (Vite Build) =====
  - type: web
    name: wastage-frontend
    env: node
    region: frankfurt
    plan: starter
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview -- --port 10000"
    workingDirectory: frontend
    autoDeploy: true
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          name: wastage-backend
          property: url